version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres15
    ports:
      - "5432:5432"
    hostname: postgres15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DATABASE}
      - LANG=ru_RU.utf8
